In [33]:
import pandas as pd
import numpy as np

In [34]:
data = {
    'Age':[45,50,42,48,52,46,44,49,51],
    'Gender':['M','F','M','F','M','F','M','F','M'],
    'Treatment':['A','A','A','B','B','B','C','C','C'],
    'BP_Before':[150,160,145,155,165,150,158,162,170],
    'BP_After':[135,140,130,125,130,120,118,122,125],
    'PainScore':[3,2,4,1,2,1,1,2,1],
    'RecoveryDays':[10,12,9,7,8,6,5,6,5],
    'Recovered':['No','No','No','Yes','No','Yes','Yes','Yes','Yes']

}

In [35]:
df = pd.DataFrame(data)

In [36]:
df

,Age,Gender,Treatment,BP_Before,BP_After,PainScore,RecoveryDays,Recovered
0,45,M,A,150,135,3,10,No
1,50,F,A,160,140,2,12,No
2,42,M,A,145,130,4,9,No
3,48,F,B,155,125,1,7,Yes
4,52,M,B,165,130,2,8,No
5,46,F,B,150,120,1,6,Yes
6,44,M,C,158,118,1,5,Yes
7,49,F,C,162,122,2,6,Yes
8,51,M,C,170,125,1,5,Yes

In [37]:
df['BP_Reduction'] = df['BP_Before'] - df['BP_After']

In [38]:
df

,Age,Gender,Treatment,BP_Before,BP_After,PainScore,RecoveryDays,Recovered,BP_Reduction
0,45,M,A,150,135,3,10,No,15
1,50,F,A,160,140,2,12,No,20
2,42,M,A,145,130,4,9,No,15
3,48,F,B,155,125,1,7,Yes,30
4,52,M,B,165,130,2,8,No,35
5,46,F,B,150,120,1,6,Yes,30
6,44,M,C,158,118,1,5,Yes,40
7,49,F,C,162,122,2,6,Yes,40
8,51,M,C,170,125,1,5,Yes,45

In [39]:
df.shape

(9, 9)

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           9 non-null      int64
 1   Gender        9 non-null      str
 2   Treatment     9 non-null      str
 3   BP_Before     9 non-null      int64
 4   BP_After      9 non-null      int64
 5   PainScore     9 non-null      int64
 6   RecoveryDays  9 non-null      int64
 7   Recovered     9 non-null      str
 8   BP_Reduction  9 non-null      int64
dtypes: int64(6), str(3)
memory usage: 780.0 bytes

In [41]:
df.describe()

,Age,BP_Before,BP_After,PainScore,RecoveryDays,BP_Reduction
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.00000
mean,47.444444,157.222222,127.222222,1.888889,7.555556,30.00000
std,3.395258,8.012144,7.189885,1.054093,2.403701,11.18034
min,42.000000,145.000000,118.000000,1.000000,5.000000,15.00000
25%,45.000000,150.000000,122.000000,1.000000,6.000000,20.00000
50%,48.000000,158.000000,125.000000,2.000000,7.000000,30.00000
75%,50.000000,162.000000,130.000000,2.000000,9.000000,40.00000
max,52.000000,170.000000,140.000000,4.000000,12.000000,45.00000

In [42]:
df.isnull().sum()

Age             0
Gender          0
Treatment       0
BP_Before       0
BP_After        0
PainScore       0
RecoveryDays    0
Recovered       0
BP_Reduction    0
dtype: int64

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df.nunique()

Age             9
Gender          2
Treatment       3
BP_Before       8
BP_After        7
PainScore       4
RecoveryDays    7
Recovered       2
BP_Reduction    6
dtype: int64

In [45]:
df.columns

Index(['Age', 'Gender', 'Treatment', 'BP_Before', 'BP_After', 'PainScore',
       'RecoveryDays', 'Recovered', 'BP_Reduction'],
      dtype='str')

#### ANOVA Test

In [46]:
from scipy.stats import f_oneway

A = df[df['Treatment']=='A']['BP_Reduction']
B = df[df['Treatment']=='B']['BP_Reduction']
C = df[df['Treatment']=='C']['BP_Reduction']

In [47]:
A

0    15
1    20
2    15
Name: BP_Reduction, dtype: int64

In [48]:
B

3    30
4    35
5    30
Name: BP_Reduction, dtype: int64

In [49]:
C

6    40
7    40
8    45
Name: BP_Reduction, dtype: int64

In [50]:
f_stat, p_value = f_oneway(A, B, C)
print("F Statistic:", f_stat)
print("P Value:", p_value)

F Statistic: 56.99999999999999
P Value: 0.00012500000000000003

In [51]:
if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant difference in BP reduction among treatments.")
else:
    print("Fail to reject the null hypothesis: No significant difference in BP reduction among treatments.")

Reject the null hypothesis: There is a significant difference in BP reduction among treatments.

### T test

A vs B

In [52]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(A,B)

print("T Statistic:", t_stat)
print("P Value:", p_value)

T Statistic: -6.363961030678928
P Value: 0.0031255892524457273

In [53]:
if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant difference in BP reduction among treatments.")
else:
    print("Fail to reject the null hypothesis: No significant difference in BP reduction among treatments.")

Reject the null hypothesis: There is a significant difference in BP reduction among treatments.

B vs C

In [54]:
t_stat, p_value = ttest_ind(B,C)
print("T Statistic:", t_stat)
print("P Value:", p_value)

T Statistic: -4.242640687119284
P Value: 0.013235599563682697

In [55]:
if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant difference in BP reduction among treatments.")
else:
    print("Fail to reject the null hypothesis: No significant difference in BP reduction among treatments.")

Reject the null hypothesis: There is a significant difference in BP reduction among treatments.

A vs C

In [56]:
t_stat, p_value = ttest_ind(A,C)
print("T Statistic:", t_stat)
print("P Value:", p_value)

T Statistic: -10.606601717798213
P Value: 0.0004472380704346324

In [57]:
if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant difference in BP reduction among treatments.")
else:
    print("Fail to reject the null hypothesis: No significant difference in BP reduction among treatments.")

Reject the null hypothesis: There is a significant difference in BP reduction among treatments.

### Z Test

In [ ]:
new_data = {
    'Age':[43,47,46,51,44,48,45,49,42,50,
           53,54,49,55,50,52,51,56,48,53,
           45,47,46,48,44,49,50,46,47,45],

    'Gender':['M','F','M','F','M','F','M','F','M','F',
              'M','F','M','F','M','F','M','F','M','F',
              'F','M','F','M','F','M','F','M','F','M'],

    'Treatment':['A']*10 + ['B']*10 + ['C']*10,

    'BP_Before':[
        148,152,147,155,149,153,150,154,146,151,
        160,168,158,170,162,166,164,172,159,167,
        159,161,160,164,158,165,166,162,163,160
    ],

    'BP_After':[
        132,134,133,138,134,134,134,139,132,133,
        129,134,129,138,129,136,133,137,128,133,
        118,118,120,120,117,122,121,119,120,118
    ],

    'PainScore':[
        3,2,3,2,3,2,3,2,4,2,
        2,1,2,1,2,1,2,1,2,1,
        1,1,1,1,2,1,1,1,1,1
    ],

    'RecoveryDays':[
        10,11,9,12,10,11,10,12,9,11,
        7,8,6,8,7,7,6,8,7,7,
        5,6,5,6,5,5,6,5,6,5
    ],

    'Recovered':[
        'No','No','No','No','No','No','No','No','No','No',
        'Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes',
        'Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes'
    ]
}

new_df = pd.DataFrame(new_data)
df_large = pd.concat([df, new_df], ignore_index=True)

# BP Reduction
df_large['BP_Reduction'] = (
    df_large['BP_Before'] - df_large['BP_After']
)

In [60]:
df_large.head()

,Age,Gender,Treatment,BP_Before,BP_After,PainScore,RecoveryDays,Recovered,BP_Reduction
0,45,M,A,150,135,3,10,No,15
1,50,F,A,160,140,2,12,No,20
2,42,M,A,145,130,4,9,No,15
3,48,F,B,155,125,1,7,Yes,30
4,52,M,B,165,130,2,8,No,35

In [62]:
df_large.shape

(39, 9)

In [65]:
from statsmodels.stats.weightstats import ztest

A = df_large[df_large['Treatment']=='A']['BP_Reduction']
B = df_large[df_large['Treatment']=='B']['BP_Reduction']
C = df_large[df_large['Treatment']=='C']['BP_Reduction']

In [66]:
A

0     15
1     20
2     15
9     16
10    18
11    14
12    17
13    15
14    19
15    16
16    15
17    14
18    18
Name: BP_Reduction, dtype: int64

In [83]:
A.tolist()

[15, 20, 15, 16, 18, 14, 17, 15, 19, 16, 15, 14, 18]

In [85]:
A.count()

np.int64(13)

In [86]:
A.var()

np.float64(3.73076923076923)

In [70]:
A.mean()

np.float64(16.307692307692307)

In [84]:
A.std()

np.float64(1.9315199276138029)

In [67]:
B

3     30
4     35
5     30
19    31
20    34
21    29
22    32
23    33
24    30
25    31
26    35
27    31
28    34
Name: BP_Reduction, dtype: int64

In [90]:
B.mean()

np.float64(31.923076923076923)

In [91]:
B.var()

np.float64(4.243589743589744)

In [92]:
B.std()

np.float64(2.0599975105785306)

In [93]:
B.count()

np.int64(13)

In [68]:
C

6     40
7     40
8     45
29    41
30    43
31    40
32    44
33    41
34    43
35    45
36    43
37    43
38    42
Name: BP_Reduction, dtype: int64

In [72]:
C.mean()

np.float64(42.30769230769231)

In [77]:
print("A vs B")
z_stat, p_val = ztest(A, B)
print(f"Z Statistic: {z_stat:.2f}")
print(f"P Value: {p_val:.10f}")

A vs B
Z Statistic: -19.94
P Value: 0.0000000000

In [80]:
if p_val < 0.05:
        print("Result: Significant Difference")
else:
    print("Result: Not Significant")

Result: Significant Difference

In [76]:
print("B vs C")
z_stat, p_val = ztest(B, C)
print(f"Z Statistic: {z_stat:.2f}")
print(f"P Value: {p_val:.10f}")

B vs C
Z Statistic: -13.70
P Value: 0.0000000000

In [81]:
if p_val < 0.05:
        print("Result: Significant Difference")
else:
    print("Result: Not Significant")

Result: Significant Difference

In [75]:
print("A vs C")
z_stat, p_val = ztest(A, C)
print(f"Z Statistic: {z_stat:.2f}")
print(f"P Value: {p_val:.10f}")

A vs C
Z Statistic: -35.53
P Value: 0.0000000000

In [82]:
if p_val < 0.05:
        print("Result: Significant Difference")
else:
    print("Result: Not Significant")

Result: Significant Difference

In [94]:
df_large

,Age,Gender,Treatment,BP_Before,BP_After,PainScore,RecoveryDays,Recovered,BP_Reduction
0,45,M,A,150,135,3,10,No,15
1,50,F,A,160,140,2,12,No,20
2,42,M,A,145,130,4,9,No,15
3,48,F,B,155,125,1,7,Yes,30
4,52,M,B,165,130,2,8,No,35
5,46,F,B,150,120,1,6,Yes,30
6,44,M,C,158,118,1,5,Yes,40
7,49,F,C,162,122,2,6,Yes,40
8,51,M,C,170,125,1,5,Yes,45
9,43,M,A,148,132,3,10,No,16
10,47,F,A,152,134,2,11,No,18
11,46,M,A,147,133,3,9,No,14
12,51,F,A,155,138,2,12,No,17
13,44,M,A,149,134,3,10,No,15
14,48,F,A,153,134,2,11,No,19
15,45,M,A,150,134,3,10,No,16
16,49,F,A,154,139,2,12,No,15
17,42,M,A,146,132,4,9,No,14
18,50,F,A,151,133,2,11,No,18
19,53,M,B,160,129,2,7,Yes,31
20,54,F,B,168,134,1,8,Yes,34
21,49,M,B,158,129,2,6,Yes,29
22,55,F,B,170,138,1,8,Yes,32
23,50,M,B,162,129,2,7,Yes,33
24,52,F,B,166,136,1,7,Yes,30
25,51,M,B,164,133,2,6,Yes,31
26,56,F,B,172,137,1,8,Yes,35
27,48,M,B,159,128,2,7,Yes,31
28,53,F,B,167,133,1,7,Yes,34
29,45,F,C,159,118,1,5,Yes,41
30,47,M,C,161,118,1,6,Yes,43
31,46,F,C,160,120,1,5,Yes,40
32,48,M,C,164,120,1,6,Yes,44
33,44,F,C,158,117,2,5,Yes,41
34,49,M,C,165,122,1,5,Yes,43
35,50,F,C,166,121,1,6,Yes,45
36,46,M,C,162,119,1,5,Yes,43
37,47,F,C,163,120,1,6,Yes,43
38,45,M,C,160,118,1,5,Yes,42

In [95]:
from scipy.stats import chi2_contingency

In [106]:
table = pd.crosstab(df_large['Treatment'], df_large['Recovered'])

In [107]:
chi2, p, dof, expected = chi2_contingency(table)

In [108]:
print("Contingency Table")
print(table)

Contingency Table
Recovered  No  Yes
Treatment
A          13    0
B           1   12
C           0   13

In [109]:
print(chi2)
print(p)
print(dof)
print(expected)

34.98857142857142
2.5253887964519484e-08
2
[[4.66666667 8.33333333]
 [4.66666667 8.33333333]
 [4.66666667 8.33333333]]

Logistic Regression

In [ ]:
df_large['Recovered'] = df_large['Recovered'].map({'No':0, 'Yes':1})

In [113]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_large['Gender'] = le.fit_transform(df_large['Gender'])   
df_large['Treatment'] = le.fit_transform(df_large['Treatment']) 
df_large['Recovered'] = le.fit_transform(df_large['Recovered'])

X = df_large.drop('Recovered', axis=1)
y = df_large['Recovered']

In [114]:
df_large.head()

,Age,Gender,Treatment,BP_Before,BP_After,PainScore,RecoveryDays,Recovered,BP_Reduction
0,45,1,0,150,135,3,10,0,15
1,50,0,0,160,140,2,12,0,20
2,42,1,0,145,130,4,9,0,15
3,48,0,1,155,125,1,7,1,30
4,52,1,1,165,130,2,8,0,35

In [115]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.875

In [127]:
import warnings as wr
wr.filterwarnings('ignore')

In [128]:
sample = [[50, 1, 1, 160, 130, 2, 7, 30]]

prediction = model.predict(sample)

In [122]:
prediction

array([1])

In [121]:
type(prediction)

numpy.ndarray

In [123]:
if prediction[0] == 1:
    print("The patient is likely to recover.")
else:
    print("The patient is unlikely to recover.")

The patient is likely to recover.